on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DNOHUB_USERNAME: ${{ secrets.DNOHUB_USERNAME }}
      DNOHUB_PASSWORD: ${{ secrets.DNOHUB_PASSWORD }}
      MASTER_URL: ${{ secrets.MASTER_URL }}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p skymp5-server
            cd skymp5-server
            mkdir -p $GITHUB_SHA && cd $GITHUB_SHA
            rm -rf .git
            git init
            git remote add origin https://$DNOHUB_USERNAME:$DNOHUB_PASSWORD@github.com/$GITHUB_REPOSITORY.git
            git fetch origin $GITHUB_SHA
            git reset --hard $GITHUB_SHA
            docker build -t skymp5-server:$(echo "${GITHUB_REF//[\/]/_}") .
            rm -rf $GITHUB_SHA
            docker run -v ~/skyrim_data_dir:/skyrim_data_dir skymp5-server:$(echo "${GITHUB_REF//[\/]/_}") npm run test
            docker rm -f scamp_merge || true
            docker rm -f scamp_$(echo "${GITHUB_REF//[\/]/_}") || true
            docker run -v ~/skyrim_data_dir:/skyrim_data_dir -p $(expr 10002 + $(echo $GITHUB_RUN_NUMBER)):8080/tcp -p $(expr 10001 + $(echo $GITHUB_RUN_NUMBER)):3000/tcp -p $(expr 10000 + $(echo $GITHUB_RUN_NUMBER)):$(expr 10000 + $(echo $GITHUB_RUN_NUMBER))/udp --name scamp_$(echo "${GITHUB_REF//[\/]/_}") --restart always -dit skymp5-server:$(echo "${GITHUB_REF//[\/]/_}") npm run start-prod -- --master $MASTER_URL --name "test:$(echo "${GITHUB_REF//[\/]/_}")" --maxPlayers 10 --port $(expr 10000 + $(echo $GITHUB_RUN_NUMBER))
          envs: GITHUB_SHA,GITHUB_REPOSITORY,DNOHUB_USERNAME,DNOHUB_PASSWORD,MASTER_URL,GITHUB_REF,GITHUB_RUN_NUMBER
          script_stop: true
          command_timeout: 6h
