on:
  push:
    branches:
      - "feature/*"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DNOHUB_USERNAME: ${{ secrets.DNOHUB_USERNAME }}
      DNOHUB_PASSWORD: ${{ secrets.DNOHUB_PASSWORD }}
      MASTER_URL: ${{ secrets.MASTER_URL }}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p skymp5-server
            cd skymp5-server
            mkdir -p $GITHUB_SHA && cd $GITHUB_SHA
            rm -rf .git
            git init
            git remote add origin https://$DNOHUB_USERNAME:$DNOHUB_PASSWORD@github.com/$GITHUB_REPOSITORY.git
            git fetch origin $GITHUB_SHA
            git reset --hard FETCH_HEAD
            docker build -t skymp5-server:${GITHUB_REF##*/} .
            rm -rf $GITHUB_SHA
            docker run skymp5-server:${GITHUB_REF##*/} npm run test
          envs: GITHUB_SHA,GITHUB_REPOSITORY,DNOHUB_USERNAME,DNOHUB_PASSWORD,MASTER_URL,GITHUB_REF
          script_stop: true
          command_timeout: 6h
