name: Reformat
on: [push, pull_request]
jobs:
    reformat:
        name: Reformat
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, '[reformat]')
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - uses: DoozyX/clang-format-lint-action@v0.14
            with:
              source: '.'
              exclude: './skyrim-platform/src/third_party'
              extensions: 'h,cpp,hpp'
              clangFormatVersion: 12
              inplace: True
          - uses: EndBug/add-and-commit@v9
            with:
              default_author: github_actor
              message: 'Committing clang-format changes'
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
